# Generated by Django 4.0.1 on 2022-05-06 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Загаловок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Загаловок')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price_usd', models.IntegerField(default=0, verbose_name='Цена в долларах')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('square', models.IntegerField(default=0, verbose_name='Площадь')),
                ('rooms', models.IntegerField(default=0, verbose_name='Кол-во комнат')),
                ('floor_number', models.IntegerField(default=0, verbose_name='Этаж дома')),
                ('floor', models.IntegerField(default=0, verbose_name='Этажность')),
                ('ceiling', models.IntegerField(default=0, verbose_name='Высота потолка')),
                ('bathroom', models.BooleanField(default=False, verbose_name='Санузел')),
                ('furniture', models.BooleanField(default=False, verbose_name='Мебилирован')),
                ('total_square', models.IntegerField(default=0, verbose_name='Общая Площадь')),
                ('house_square', models.IntegerField(default=0, verbose_name='Жилая Площадь')),
                ('electricity', models.BooleanField(default=False, verbose_name='Электричество')),
                ('gas', models.BooleanField(default=False, verbose_name='Газ')),
                ('heating', models.BooleanField(default=False, verbose_name='Отопление')),
                ('water', models.BooleanField(default=False, verbose_name='Вода')),
                ('sewerage', models.BooleanField(default=False, verbose_name='Канализация')),
                ('repair', models.CharField(choices=[('V1', 'Евроремонт'), ('V2', 'Средний'), ('V3', 'Старый'), ('V4', 'Требует ремонта'), ('V5', 'Коробка')], max_length=300, null=True, verbose_name='Ремонт')),
                ('building_type', models.CharField(choices=[('V1', 'Панельная'), ('V2', 'Кирпичная'), ('V3', 'Древесная')], max_length=300, null=True, verbose_name='Тип строения')),
                ('plan', models.CharField(choices=[('V1', 'Раздельная'), ('V2', 'Смежная'), ('V3', 'Раздельно-смежная')], max_length=300, null=True, verbose_name='Планировка')),
                ('availibility', models.BooleanField(default=False, verbose_name='Availibility')),
                ('parking', models.BooleanField(default=False, verbose_name='Парковка')),
                ('is_favourite', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estate', verbose_name='recomendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='recomendation')),
            ],
            options={
                'verbose_name': 'Recomendation',
                'verbose_name_plural': 'Recomendations',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.FileField(blank=True, null=True, upload_to='', verbose_name='Галерея')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to='app.estate', verbose_name='Flat')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_favourites', to='app.estate', verbose_name='Пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
    ]
