# Generated by Django 4.0.1 on 2022-05-07 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='bathroom',
            field=models.BooleanField(blank=True, default=False, verbose_name='Санузел'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='building_type',
            field=models.CharField(blank=True, choices=[('V1', 'Панельная'), ('V2', 'Кирпичная'), ('V3', 'Древесная')], max_length=300, null=True, verbose_name='Тип строения'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='app.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='ceiling',
            field=models.IntegerField(blank=True, default=0, verbose_name='Высота потолка'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='electricity',
            field=models.BooleanField(blank=True, default=False, verbose_name='Электричество'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='floor',
            field=models.IntegerField(blank=True, default=0, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='floor_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Этаж дома'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='furniture',
            field=models.BooleanField(blank=True, default=False, verbose_name='Мебилирован'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='gas',
            field=models.BooleanField(blank=True, default=False, verbose_name='Газ'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='heating',
            field=models.BooleanField(blank=True, default=False, verbose_name='Отопление'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='house_square',
            field=models.IntegerField(blank=True, default=0, verbose_name='Жилая Площадь'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='plan',
            field=models.CharField(blank=True, choices=[('V1', 'Раздельная'), ('V2', 'Смежная'), ('V3', 'Раздельно-смежная')], max_length=300, null=True, verbose_name='Планировка'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='repair',
            field=models.CharField(blank=True, choices=[('V1', 'Евроремонт'), ('V2', 'Средний'), ('V3', 'Старый'), ('V4', 'Требует ремонта'), ('V5', 'Коробка')], max_length=300, null=True, verbose_name='Ремонт'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='rooms',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кол-во комнат'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='sewerage',
            field=models.BooleanField(blank=True, default=False, verbose_name='Канализация'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='square',
            field=models.IntegerField(blank=True, default=0, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='total_square',
            field=models.IntegerField(blank=True, default=0, verbose_name='Общая Площадь'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='water',
            field=models.BooleanField(blank=True, default=False, verbose_name='Вода'),
        ),
        migrations.AlterField(
            model_name='view',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estate', verbose_name='recomendations'),
        ),
        migrations.AlterField(
            model_name='view',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
