# Generated by Django 4.0.1 on 2022-05-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_estate_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_detail', to='app.category', verbose_name='Category'),
        ),
    ]
